image: barichello/godot-ci:3.4.2

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: un-monstre-terrifiant

linux:
  when: manual
  stage: export
  tags:
    - docker
  script:
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  when: manual
  stage: export
  tags:
    - docker
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

web:
  when: manual
  stage: export
  tags:
    - docker
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web


# Itch.io Deploy
itchio:linux:
  when: manual
  stage: deploy
  tags:
    - docker
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux --userversion $CI_COMMIT_TAG
  dependencies:
    - linux
  only:
    - tags

itchio:windows:
  when: manual
  stage: deploy
  tags:
    - docker
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows --userversion $CI_COMMIT_TAG
  dependencies:
    - windows
  only:
    - tags

itchio:web:
  when: manual
  stage: deploy
  tags:
    - docker
  script:
    - butler push ./build/web $ITCHIO_USERNAME/$ITCHIO_GAME:web --userversion $CI_COMMIT_TAG
  dependencies:
    - web
  only:
    - tags
